### ISSUE TITLE
Broken gitprompt on a lack of installed git

### ISSUE THREAD

**Issue by Felixoid** [woefe/git-prompt.zsh#10]
Hey. If git is not installed then the status is always `[|✔]`

The way to reproduce is in the asciicast [![cast](https://asciinema.org/a/PlEPGiMs47uIRu6LxA4Lh31uA.png)](https://asciinema.org/a/PlEPGiMs47uIRu6LxA4Lh31uA)

**Comment by woefe** [comment]
Thanks. Fixed in ac20119.

**Comment by Felixoid** [comment]
Could you create a new tag, please?

**Comment by woefe** [comment]
Sure. https://github.com/woefe/git-prompt.zsh/releases/tag/v2.0.1
