### ISSUE TITLE
100% CPU load when async is on

### ISSUE THREAD

**Issue by ohle** [woefe/git-prompt.zsh#12]
Hi,

I've noticed that every zsh process currently displaying a prompt is at 100% CPU load when using git-prompt. This does not happen when setting `ZSH_GIT_PROMPT_NO_ASYNC=1`

I'm using `master` (5d4d63d9) and zsh 5.0.2

**Comment by woefe** [comment]
I cannot reproduce it. I did not find a way to get zsh 5.0.2 and a version of Git above 2.11. on the same system. I tried:
- compiling zsh from source on my system, but no luck
- using zsh-users/zsh-docker, but that's based on Debian Jessie. So no recent version of git. And the ppa did not work.
- Trying to build an old version of Arch's PKGBUILD. But the zsh release archive 404s.

I give up. Sorry. How did you manage to get a 7 year old version of zsh together with Git >2.11?

You can still try troubleshooting. Load zsh without a config and source the prompt.
```
zsh -f
source path/to/git-prompt.zsh
```
If the problem goes away with this, then your config or some other plugin interfere with the prompt. Do you override zle widgets (e.g. reset-prompt)? Do you use any precmd hooks?

And also try your config in a newer version of zsh, if possible.

**Comment by ohle** [comment]
I didn't realize it was *that* old (it's a Ubuntu 14.04 system with git from a ppa).

I can confirm it doesn't happen with zsh 5.7 or even 5.4, so I'm closing this. No use debugging such an old version.
