### ISSUE TITLE
Ctrl+C doesn't move to a new line until I type.

### ISSUE THREAD

**Issue by Corey-Keller** [woefe/git-prompt.zsh#14]
I assume that this is probably a matter of changing a setting that I'm missing, but here's the issue:
In a standard terminal, if I hit Ctrl+C 5 times, it will make 5 new lines like it does when enter is pressed. With this prompt, there is no change until I type again, and then I only get 1 new line. I assumed it was an async thing, but changing ZSH_GIT_PROMPT_NO_ASYNC had no effect on that. Is there a way to change this behavior?

**Comment by hurricanehrndz** [comment]
Corey-Keller,

A video would probably help, I use this as a base for my prompt and I don't see any issue like this.

**Comment by Corey-Keller** [comment]
Upon further inspection, it turns out that this issue only happens with [CentOS on WSL](https://github.com/yuk7/CentWSL). So I'll go ahead and close this.
