### ISSUE TITLE
Tag name

### ISSUE THREAD

**Issue by rnc** [woefe/git-prompt.zsh#15]
This is an idea for a potential feature enhancement.

Sometimes I have a tag checked out which results in a prompt like
```
[:ab18db6|✔] ❯
```
Running `git tag --points-at` shows
```
  foo-3.8.1-CR1
  foo-3.8.1-CR2
```
Now this would completely clutter the left hand prompt if it was placed there so one possibility is an optional extra feature that would enable e.g. `gitrprompt` which would return the list of tags (if any) suitable for embedding inside the RPROMPT.
For example - as a non-async example:
```
        function git_tag_display()
        {
            local tags="$([[ -d .git ]] && git tag --points-at | awk '{ printf("%s", NR == 1 ? $0 : ","$0); }')"
            [[ -n "$tags" ]] && echo "%{$fg_bold[magenta]%}$ZSH_THEME_GIT_PROMPT_PREFIX$tags$ZSH_THEME_GIT_PROMPT_SUFFIX"
        }
```
Which I then use inside
```
function prompt_updater ()
        {
            # Prompt turns red if the previous command didn't exit with 0
            PROMPT="$(gitprompt)$PROMPT_JAVA$PROMPT_EXTRA $PROMPT_HAT%(?.%B%F{magenta}.%F{red})${PROMPT_SYMBOL}%f%b "
            RPROMPT="%{"$'\e[0;35m'"%}$((( ${+VIRTUAL_ENV} )) && basename $VIRTUAL_ENV)$(git_tag_display)%{"$'\e[00m%}'" %T"
        }
```
Obviously it would be better if `git_tag_display` was async and integrated into the tool :-)

**Comment by woefe** [comment]
I like the idea :+1: 

I will think about how this can be done. I probably want to build it in a way that users can configure which information is shown with gitprompt and gitrprompt.

**Comment by woefe** [comment]
I implemented a secondary prompt in eaa14ee. Let me know what you think. I decided against making it as modular as I originally intended, because of backwards compatibility.

**Comment by rnc** [comment]
Nice!
Few comments : 

- I don't think you need HEAD in the `points-at` - according to my man page (git-2.21.0-1.fc30.x86_64) it defaults to HEAD if not specified.
- Where did you get the 'tag' symbol from (e.g. font) - it doesn't display for me.
- While my personal preference is to have `ZSH_THEME_GIT_PROMPT_TAGS_SEPERATOR=","` without space separators its easy enough to override.

**Comment by rnc** [comment]
I found the tag symbol within `unifont-fonts`. I am running Fedora 30 and it is in unifont-12.0.01-1.fc30.src.rpm - from https://savannah.gnu.org/projects/unifont
Perhaps this could be added to the README as a note?

**Comment by woefe** [comment]
Thanks!
- I just wanted to make it explicit. I think implicit defaults are harder to understand, because you need to know the defaults. 
- Good point! The tag symbol is the [label emoji](https://emojipedia.org/label). I will add it to the README. Personally, I use https://github.com/eosrei/twemoji-color-font
- I like it more with the space, because it is more natural to read. I will leave it as default

**Comment by woefe** [comment]
closed in v2.2.0

**Comment by rnc** [comment]
Thanks!

**Comment by woefe** [comment]
I just fixed the typo in `ZSH_THEME_GIT_PROMPT_TAGS_SEPERATOR`. Unfortunately this change is not backwards compatible and you have to change it to `ZSH_THEME_GIT_PROMPT_TAGS_SEPARATOR` (with an A) the next time you update your prompt to v2.2.1 or newer.

I wanted to have it corrected and I hope not many people already changed their configs.
So sorry about this!

**Comment by rnc** [comment]
Apologies for not noticing it in my review. Sorry!
