### ISSUE TITLE
Release the soft

### ISSUE THREAD

**Issue by Felixoid** [woefe/git-prompt.zsh#2]
Hello Wolfgang.

Thank you for an awesome pure-shell solution! It works very well and allows to make portable solutions like https://github.com/Felixoid/dotfiles/commit/151d3434224f031181d9113cafd7fd94382a3f1b.

Btw, I've maintained a [git version](https://aur.archlinux.org/packages/git-prompt.zsh-git/) of a package for Arch linux user repository and would like to create a normal one as well. I'll appreciate if you create release tags, which is necessary for the usual package.

**Comment by woefe** [comment]
I'm happy to see that you like it :smile: and also thanks for the AUR package.

I've just tagged [v1.0.0](https://github.com/woefe/git-prompt.zsh/releases/tag/v1.0.0).

Regarding your AUR package: Usually, the `# Maintainer:` comment at the beginning of the PKGBUILD refers to the maintainer of the package, not the maintainer of the software -- which is you, not me.
