### ISSUE TITLE
Branch info does't show

### ISSUE THREAD

**Issue by cposture** [woefe/git-prompt.zsh#21]
after install, the Branch info does't show under the git repo

git version 2.11.0
zsh 5.3.1 (x86_64-debian-linux-gnu)

![image](https://user-images.githubusercontent.com/8305198/95250176-4c906400-084c-11eb-83b6-89dc59b2c8c7.png)

**Comment by woefe** [comment]
Thanks for your report. What is the output of 
```
git status --branch --porcelain=v2
```
and
```
print -P $(gitprompt)
```
Both run from within a Git directory.

Is your System a Debian 9?

**Comment by woefe** [comment]
Okay. I can reproduce the Issue inside a Debian 9 Docker container.

**Comment by woefe** [comment]
The Git version on Debian 9 does not have the `--no-optional-locks` option and therefore fails to execute properly, which was introduced in Git version 2.15.0 (https://github.com/git/git/blob/master/Documentation/RelNotes/2.15.0.txt). It seems that this option can also be set with GIT_OPTIONAL_LOCKS=0 env variable, which would make it backwards compatible.

**Comment by woefe** [comment]
I think it's fixed in 1016089.

Can you update and try again?

**Comment by cposture** [comment]
@woefe https://github.com/woefe/git-prompt.zsh/commit/1016089f8d7fcda8cea45db1f26083e17287a9b1 It works for me, thanks
