### ISSUE TITLE
Only right side status is needed

### ISSUE THREAD

**Issue by tkono1** [woefe/git-prompt.zsh#25]
I would like to show only git status at the right side of prompt line, but it overrides original prompt also. It seems following part of the script overrides PROMPT. Is it `possible` to add new option to choose whether override PROMPT or not?

```
# Override PROMPT if it does not use the gitprompt function
[[ "$PROMPT" != *gitprompt* && "$RPROMPT" != *gitprompt* ]] \
    && PROMPT='%B%40<..<%~ %b$(gitprompt)' \
    && PROMPT+='%(?.%(!.%F{white}❯%F{yellow}❯%F{red}.%F{blue}❯%F{cyan}❯%F{g    reen})❯.%F{red}❯❯❯)%f '
```

**Comment by woefe** [comment]
How do you load the git-prompt.zsh plugin? Try setting the `PROMT` (or `RPROMPT`) after you load the git-prompt.zsh.

**Comment by tkono1** [comment]
Hi woefe, thanks for your reply!

I chose manual installation. And just added two lines below to my ~/.config/zsh/.zshrc after PROMPT.

```
source ~/.config/zsh/functions/git-prompt.zsh
source ~/.config/zsh/functions/examples/rprompt.zsh
```
The prompt is,
`~/Workspace/config ≻≻≻                                             ≺ master⟳  ✔`

I moved the lines before PROMPT. It just works! Thanks for your advice.
`[tkono1@mbp:~/Workspace/config]%                                   ≺ master⟳  ✔`
