### ISSUE TITLE
stopped working after async

### ISSUE THREAD

**Issue by Mellbourn** [woefe/git-prompt.zsh#3]
It sounds great that you are adding async functionality!

Unfortunately, after I upgrade to latest, my git prompt disappears. The `gitprompt` command no longer gives any output.

If do a `git reset --hard v1.0.0` then everything starts working again. It is specifically commit `31d715d` that breaks it for me.

I figured out that I'm supposed to install `zsh-async`, and I have done so, but it does not repair the problem.

So something in the latest commits broke it for me.

Is there anything I can do to troubleshoot it?

I don't think it is relevant, but I install both zsh-async and git-prompt using `zplug`, like so:
```
zplug "mafredri/zsh-async", from:"github", use:"async.zsh"
zplug "woefe/git-prompt.zsh", from:github, as:plugin, use:git-prompt.zsh
```

zpty gives some output:
````
 > zpty
(73376) git_prompt_worker: _async_worker -p 72994
````

I've tried to analyze what happens with `echo` statements and it looks like neither `_zsh_git_prompt_git_status` nor `_zsh_git_prompt_callback` is ever called.

Calling `_zsh_git_prompt_git_status` manually results in an output that looks like a correct prompt.

`$_ZSH_GIT_PROMPT_STATUS_OUTPUT` is never set.

I'm on macOS Mojave 10.14.3, zsh 5.7.1, git hash a1221c of git-prompt.zsh

**Comment by Felixoid** [comment]
Could it be possible to make async optional, maybe?

**Comment by woefe** [comment]
To figure out if it is a macOS issue, or related to your config or zplug, you could try my zsh config which I know works on various Linux environments (I've tested Arch, Ubuntu, WSL, Termux on Android)

```
git clone --depth=1 --recursive https://github.com/woefe/dotfiles.git dotfiles-woefe
cd dotfiles-woefe/zsh/
HOME=$PWD zsh -f
source .zshrc  # ignore the error that .aliases is missing
```
The prompt should now be something like this:
```
~ [master|…2] ❯❯❯
```

To be honest, I am not entirely happy with zsh-async, see #4.

**Comment by Mellbourn** [comment]
When I try your environment, it does work. And I really like the async part.

**Comment by Mellbourn** [comment]
I finally found what was causing the problem for me. I have installed https://github.com/sharkdp/bat and created an alias 
```
alias cat=bat
````
If I remove that alias, git-prompt starts working again (with async, and zplug)

**Comment by woefe** [comment]
lol, weird bug. zsh-async seems to use [cat to communicate with the async job](https://github.com/mafredri/zsh-async/blob/master/async.zsh#L34). bat is awesome, I use it myself, but have not aliased it. Maybe the problem is, that bat is automatically paging? I will test it some more on my system and report it to zsh-async.
