### ISSUE TITLE
Question: a global option not to show counts?

### ISSUE THREAD

**Issue by telemachus** [woefe/git-prompt.zsh#39]
First and foremost, thank you. This is an outstanding prompt and very easy to work with.

Now my question: would you consider a pull request that adds a global option to disable showing counts? (I'm thinking something like `ZSH_GIT_PROMPT_DISABLE_COUNTS`, but I'm happy to take suggestions about names.) The idea is that if the option is turned on, then things like staged, unstaged, and untracked would show their symbol but not a count.

**Comment by woefe** [comment]
Nice to hear that you like it!

Would the setting suppress all text content and only show the symbols? I.e. also suppress branch name, upstream, ahead, behind?

**Comment by telemachus** [comment]
> Would the setting suppress all text content and only show the symbols? I.e. also suppress branch name, upstream, ahead, behind?

I was thinking for a toggle only to remove the numbers. So the prompt would still show whatever text and symbols were defined for that section. That said, I understand that I may be the only person asking for this.

**Comment by woefe** [comment]
Okay, got it. I'd be open to a PR.

Maybe it makes sense to have two settings. One `ZSH_GIT_PROMPT_SHOW_LOCAL_COUNTS` to show/suppress the counts in the [local_status](https://github.com/woefe/git-prompt.zsh/blob/55f40bdfb287122ea50c1c01ef056ca7dac175e5/README.md?plain=1#L21).  And `ZSH_GIT_PROMPT_SHOW_TRACKING_COUNTS` to show/suppress the counts in the [tracking_status](https://github.com/woefe/git-prompt.zsh/blob/55f40bdfb287122ea50c1c01ef056ca7dac175e5/README.md?plain=1#L17)

**Comment by woefe** [comment]
Closed in #43
