### ISSUE TITLE
move away from zsh-async

### ISSUE THREAD

**Issue by woefe** [woefe/git-prompt.zsh#4]
Some issues came up with the current async implementation:

- The async worker seems to crash sometimes:
   ```
   async_job:zpty:12: no such pty command: git_prompt_worker
   ```
- Adds a dependency to zsh-async. The external dependency is harder to package (e.g. in an AUR package)
- Might not work on every platform or in every scenario

zsh-users/zsh-autosuggestions uses an implementation without zpty and zsh-async.
- https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/async.zsh
- https://github.com/zsh-users/zsh-autosuggestions/pull/338

**Comment by Mellbourn** [comment]
I just want to comment that I *love* the performance improvement after you started using `zsh-async`. I think it makes `git-prompt.zsh` the far and away best git prompt I've tried, and I've tried quite a few.
So, if you give up on `zsh-async`, I hope you replace it with some other async functionality.

**Comment by woefe** [comment]
Yes, of course, async will stay. The idea is to implement async functionality similar to what [zsh-users/zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions/) is doing

**Comment by woefe** [comment]
I've removed the zsh-async dependency. So far it has been working great for me on various Linux environments. @Mellbourn,  can you check if it is working properly on your macOS setup, please? If it's working, I will probably tag a new release.

**Comment by Mellbourn** [comment]
Yes. It works great on macOS!

**Comment by Mellbourn** [comment]
Today I noticed a problem:

In one of my shells, which had been open for a long time, and where I'd finished a large rebase, the prompt stopped updating. It kept showing the status just after the rebase finished (indicating lots of commits to push, even though they were already pushed)

I tried changing directory and checking out a different branch, but the prompt still did not update. Not even changing directory to another repo or outside any repo updated the prompt.

In other shells, the prompt kept updating.

This was after zsh-async was removed. But can't say for sure this issue is because it was removed.

**Comment by woefe** [comment]
Thanks for all your feedback. I've fixed some minor and probably unrelated things this morning. However there might be a chance that these changes solve the issue you experienced. Did you run into this issue again?

If you experience this again, do:
1. `print -P $(_zsh_git_prompt_git_status)`. If this does not show the correct prompt, the issue is not related to async, but probably due to unexpected git status output. I'm pretty confident that this will print the correct prompt, since the prompt kept updating in other shells.
2. `_zsh_git_prompt_async_request; sleep 5; print -P $(gitprompt)`. If this shows the correct prompt, then it is not async related.
3. Values of pid, fd and try to read from fd might be useful for further investigation
    ```
    # first remove the precmd hook to avoid interference
    add-zsh-hook -d precmd _zsh_git_prompt_precmd_hook
    echo $_ZSH_GIT_PROMPT_ASYNC_PID    
    echo $_ZSH_GIT_PROMPT_ASYNC_FD
    cat <&$_ZSH_GIT_PROMPT_ASYNC_FD
    ```
    At this point the prompt cannot update any more. You must add the precmd hook again to re-enable it: `add-zsh-hook precmd _zsh_git_prompt_precmd_hook`.

**Comment by Mellbourn** [comment]
So far I have not run into this issue again.
I will remember to troubleshoot it according to your instructions if it
happens again.
