### ISSUE TITLE
Does not show untracked

### ISSUE THREAD

**Issue by chx** [woefe/git-prompt.zsh#47]
Amazing work, thanks.

![2024-09-25 04 13 57](https://github.com/user-attachments/assets/02a0ca25-626a-4949-9d10-2f2375337cd1)

`$ZSH_THEME_GIT_PROMPT_UNTRACKED` is `…`, `$ZSH_GIT_PROMPT_SHOW_TRACKING_COUNTS` is 1, `$ZSH_GIT_PROMPT_SHOW_LOCAL_COUNTS` is also 1.

Prompt looks like this:

```
function lprompt {
  local git='$(gitprompt)'
  local cwd="${PR_BRIGHT_CYAN}%B%1~%b"
  PROMPT="${PR_RESET}${PR_BRIGHT_RED}➜  ${cwd} ${git}${PR_BRIGHT_YELLOW}✗ ${PR_RESET}"
}
```

And it works... except for untracked. I have seen ✚1 for example.

**Comment by telemachus** [comment]
Out of curiosity, what does the following show?

```shell
printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
```

**Comment by chx** [comment]
`ZSH_GIT_PROMPT_THEME_UNTRACKED=`

**Comment by telemachus** [comment]
Okay, while playing with this myself and trying to test, I found that the `ZSH_GIT_PROMPT...` vars were "sticky" in a weird way. Please try this.

```shell
unset ZSH_GIT_PROMPT_THEME_UNTRACKED
source /path/to/wherever/you/keep/git-prompt.zsh
```

**Comment by chx** [comment]
➜  smartsheethelp [staging↓3↑1|✔] ✗ printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
ZSH_GIT_PROMPT_THEME_UNTRACKED=
➜  smartsheethelp [staging↓3↑1|✔] ✗ rm docroot/x
➜  smartsheethelp [staging↓3↑1|✔] ✗ printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
ZSH_GIT_PROMPT_THEME_UNTRACKED=
➜  smartsheethelp [staging↓3↑1|✔] ✗ touch docroot/x
➜  smartsheethelp [staging↓3↑1|✔] ✗ printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
ZSH_GIT_PROMPT_THEME_UNTRACKED=

**Comment by chx** [comment]
```
➜  smartsheethelp [staging↓3↑1|✔] ✗ unset ZSH_GIT_PROMPT_THEME_UNTRACKED
➜  smartsheethelp [staging↓3↑1|✔] ✗ source ~/.zsh/git-prompt.zsh/git-prompt.zsh
➜  smartsheethelp [staging↓3↑1|✔] ✗
➜  smartsheethelp [staging↓3↑1|✔] ✗ printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
ZSH_GIT_PROMPT_THEME_UNTRACKED=
➜  smartsheethelp [staging↓3↑1|✔] ✗ rm docroot/x
➜  smartsheethelp [staging↓3↑1|✔] ✗ printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
ZSH_GIT_PROMPT_THEME_UNTRACKED=
➜  smartsheethelp [staging↓3↑1|✔] ✗ touch docroot/x
➜  smartsheethelp [staging↓3↑1|✔] ✗ printf "ZSH_GIT_PROMPT_THEME_UNTRACKED=%s\n" "$ZSH_GIT_PROMPT_THEME_UNTRACKED"
ZSH_GIT_PROMPT_THEME_UNTRACKED=
```

**Comment by chx** [comment]
I am noting `ag ZSH_GIT_PROMPT_THEME_UNTRACKED ~/.zsh/git-prompt.zsh/` comes back empty

**Comment by chx** [comment]
Oh dear. 

My bad! I had

```
[status]
        showUntrackedFiles = no
```

in global gitconfig. Not sure why I did that.

Sorry for the noise.
