### ISSUE TITLE
Add remote branch name

### ISSUE THREAD

**Issue by woefe** [woefe/git-prompt.zsh#5]
If there is demand for it, the name of the remote and branch could be added to the prompt. E.g. `[ remote/remotebranchname localbranchname ↓2↑3| ...]`

Implementing this should be fairly straightforward, because `git status` already outputs this information. It is just a matter of parsing it and adding code to optionally show it.

**Comment by jerrywdlee** [comment]
Just created a pull request for that. 
https://github.com/woefe/git-prompt.zsh/pull/17
