### ISSUE TITLE
Support for plugin managers and streamline installation 

### ISSUE THREAD

**Issue by woefe** [woefe/git-prompt.zsh#6]
Disclaimer: I do not use a plugin manager for Zsh myself and have no idea how they handle plugins. Do they require a special directory layout etc? Let me know below what has to be done for the plugin manager of you choice. Also, PRs are welcome

**Comment by aryklein** [comment]
I've tried **oh-my-zsh**  for few days and I think this is the way to create plugins:

1) Create a file named `<plugin-name>.plugin.zsh`
2) Stick it in `$ZSH/custom/<plugin-name>/` directory
3) Enable it with `plugins=(... <plugin-name>)` in your `.zshrc` file.

More information here:
https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#adding-a-new-plugin

BTW, I don't use plugin manager anymore. This plugin is awesome ;-)

**Comment by Mellbourn** [comment]
I install it using `zplugin`, it is fairly straightforward
```
zplugin ice atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin load woefe/git-prompt.zsh
```

**Comment by woefe** [comment]
Added `zplugin` instructions in c27af98

**Comment by woefe** [comment]
Closing, because most popular plugin managers seem to be covered by now.
